version: "3.9"

services:
  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: teefan_app
      POSTGRES_PASSWORD: teefan_app
      POSTGRES_DB: teefan_app_development
    ports:
      - "3000:3000"
      - "3005:3005"
    volumes:
      - web_data:/var/www/teefan_app

  webpack_dev_server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - web_data:/var/www/teefan_app

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis

  database:
    image: postgres:12.7
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: teefan_app
      POSTGRES_PASSWORD: teefan_app
      POSTGRES_DB: teefan_app_development
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  web_data:
  redis_data:
  database_data:
