version: "3"

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  redis:
    image: redis:6.2

  postgres:
    image: postgres:12.7
    environment:
      POSTGRES_DB: three_kingdoms_development
      POSTGRES_USER: threekingdoms
      POSTGRES_PASSWORD: threekingdoms
      POSTGRES_ROOT_PASSWORD: rootpassword
