version: "3"

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  database:
    image: postgres:12.7
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: threekingdoms
      POSTGRES_PASSWORD: threekingdoms
      POSTGRES_DB: three_kingdoms_development
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
