default: &default
  adapter: postgresql
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= Settings.db.username %>
  password: <%= Settings.db.password %>
  host: <%= Settings.db.host %>
  port: <%= Settings.db.port %>

development:
  <<: *default
  database: three_kingdoms_development

test:
  <<: *default
  database: three_kingdoms_test

production:
  <<: *default
  database: three_kingdoms_production
  username: threekingdoms
  password:
