default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= Settings.db.username %>
  password: <%= Settings.db.password %>
  host: <%= Settings.db.host %>
  port: <%= Settings.db.port %>

development:
  <<: *default
  database: teefan_app_development

test:
  <<: *default
  database: teefan_app_test

production:
  <<: *default
  database: teefan_app_production
  username: teefan_app
  password:
