default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV.fetch('POSTGRES_USER', Settings.db.user) %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', Settings.db.password) %>
  host: <%= ENV.fetch('POSTGRES_HOST', Settings.db.host) %>
  port: <%= ENV.fetch('POSTGRES_PORT', Settings.db.port) %>

development:
  <<: *default
  database: teefan_app_development

test:
  <<: *default
  database: teefan_app_test

production:
  <<: *default
  database: teefan_app_production
