# pulled from repo
name: "Brakeman"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '20 0 * * 5'

jobs:
  brakeman:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # If running on a self-hosted runner, check it meets the requirements
      # listed at https://github.com/ruby/setup-ruby#using-self-hosted-runners
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: Brakeman run
        continue-on-error: true
        run: bundle exec brakeman -f sarif -o brakeman.sarif.json .

      - name: Upload Brakeman Sarif output
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: brakeman.sarif.json
