# pulled from repo
name: "Rails CI"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  rails:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # If running on a self-hosted runner, check it meets the requirements
      # listed at https://github.com/ruby/setup-ruby#using-self-hosted-runners
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.12.0
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: RSpec run
        run: |
          bash -c "
            bundle exec rspec
            [[ $? -ne 2 ]]
          "

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/index.html
